### ISSUE TITLE
Severe - Compatibility issue with FE-base

### ISSUE THREAD

**Issue by JanssenBrm** [APISuite/apisuite-be#106]
**Summary**

We noticed that the backend versions have a compatibility issue with FE code, specifically the retrieval of the translations. With the latest version of both the FE and BE components, the portal is not able to retrieve any translations, falling back to the default translations. 

When looking at the latest commit regarding the translation controller, the concept of an extension is introduced: 
https://github.com/APISuite/apisuite-be/commit/2277bf873796efc1ba8f4a160ad2ffa347efb17b 

This means that current requests (such as `/translations/en-US`) are resulting in a 404 error. The URLs should be updated to `translations/en-US/core`. However, this does create a compatibility issue as the fe-base was not adapted for this change (https://github.com/APISuite/fe-base/blob/next/lib/Provider.tsx#L26-L29). 

There was no pull request created as there are multiple options to solve the issue:
- Support a default value (core) in the backend to make sure current versions keep on working.
- Update the code of the FE to send the extension with the request.

---
**This is quite severe as we do have some legal requirements to show the correct translations**

---
**Expected behavior**

The custom translations are loaded in the portal application.

**Steps To Reproduce**

This can easily be reproduced by opening a portal with the latest versions. If you look at the requests that the portal sends, you will notice that the `/translations` is failing with a 404 status code.

**Environment**

- FE: 1.49.1
- BE: 5.17.15

**Comment by Joao-Castilho** [comment]
Bug fixed, now allow legacy mode and extension mode, please update.
