### ISSUE TITLE
Unable to introspect tokens due to missing subscription plans

### ISSUE THREAD

**Issue by JanssenBrm** [APISuite/apisuite-be#82]
**Summary**

Since v5.10.0 we are experiencing issues when users try to open the billing page on our marketplace. After some investigation, we've found that the billing extension was not able to introspect the incoming cookie auth through the APISuite backend.

Some strange is happening because, when looking at the logs of the backend they mention that the introspect request finished with a 200 OK status. However, when you debug the actual processing of the request, an error is generated in the  `middleware/plan-control.js` file.  In our case we do not have any subscription plans defined in the `subscription_plan` table. This is causing the following errors:

- Based on the code, it will then set the type value to `full` of `res.loggedInUser`. However, this property seems to be undefined in our case. In other middleware, I noticed that the code is setting `res.locals.loggedInUser`, but I am not sure if they represent the same property.
- Even if the value could be set, the code is generating a new error as it is trying to extract information from the first plan `plan[0]` - even though there are no plans in our case.

So I am not quite sure how to resolve this issue. It could be that we are missing some vital configuration but I cannot seem to find any documentation on how to create the subscription plans.

**Expected behavior**

- The introspect call should show the correct code in the backend logs if the request failed. 
- In case subscription plans are not required in the backend, the `plan-control.js` should not return any error

**Steps To Reproduce**

1. Setup an environment with the latest versions of the backend, marketplace- and billing extensions
2. Start the front end with the latest version of the billing ui extension
3. Login to the application and go to the billing page

**Comment by cloudokitroni** [comment]
fixed with release [5.13.5](https://github.com/APISuite/apisuite-be/releases/tag/v5.13.5)
