### ISSUE TITLE
Error during migrations

### ISSUE THREAD

**Issue by JanssenBrm** [APISuite/apisuite-be#92]
Dear,

We are currently receiving errors when executing the latest migrations. This is happening when updating our backend from 5.12.0 to 5.13.5. During these migrations we get the following message:

`ERROR: WHERE parameter "org_id" has invalid "undefined" value`

This is being caused by the following code:
https://github.com/APISuite/apisuite-be/blob/e13d033e5f947a61d2497cc810d96e00e419ba57/migrations/20220510122118-adds-default_resources.js#L16

From how I read the code, the line of code is using `org_id`. However, when looking at the definition of a record, a record has a member `orgId` and not `org_id`.

**Comment by JanssenBrm** [comment]
The issue seems to be resolved with the latest changes.

**Comment by LuisTroni** [comment]
Cheers
